### ISSUE TITLE
[DOCS]Improve the readme.md file 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Solidity-Pathshala#1]
Hey if anyone interested in making the readme.md file correct and good looking 
Then feel free to  take this issue

**Comment by khushimarothi** [comment]
I can add the contributors section to the readme

**Comment by Vikash-8090-Yadav** [comment]
ya u can but along with this please add  the  hack club rait logo  as well the lables  . 
<br>


![Screenshot from 2022-07-26 23-13-06](https://user-images.githubusercontent.com/85225156/181076922-9abf665b-4a70-4811-ba67-20b4dbe2cf7d.png)


**The logo of the HACK CLUB RAIT IS ATTACHED BELOW** 


![1632670084686-1](https://user-images.githubusercontent.com/85225156/181077201-07455734-42d9-43a1-b7bd-c5b855711afa.jpg)

**add these after the Cover image  .** 

**PS : Adjust the height and width accordingly .**
