### ISSUE TITLE
Faucet Smart Contract

### ISSUE THREAD

**Issue by nirban256** [Vikash-8090-Yadav/Solidity-Pathshala#100]
I want to create a faucet smart contract for a custom ERC20 token giving a fixed amount of tokens to the address requested it after a specific interval of time.
I would have to create two contracts one for the token and the other for the faucet smart contract.

Can I work on this? @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
Great @nirban256 start working on this

**Comment by nirban256** [comment]
Ok

**Comment by nirban256** [comment]
in which folder do I need to keep the folder? @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
level2 @nirban256
