### ISSUE TITLE
Getting real time data feeds  in  smart contract with Chainlink 

### ISSUE THREAD

**Issue by test-account09** [Vikash-8090-Yadav/Solidity-Pathshala#102]
Hii sir , please assign this issue to me , 
In this i want create a smart contract   which can get     the real time data feeds  with the help of the  chainLink  API . 

The folder structure is ; Level1/Chainlink/RealTimedata.sol

**Comment by Vikash-8090-Yadav** [comment]
Great @test-account09 , Start  working on this
