### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by kunal232i** [Vikash-8090-Yadav/Solidity-Pathshala#103]
### Project title
Calculator

### Project Description
Calculator smart contract using Remix (Math operations)

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
yes, Hacktobefest
<hr/>

**Comment by kunal232i** [comment]
Can you assign this project to me..?

**Comment by Vikash-8090-Yadav** [comment]
ya sure @kunal232i

**Comment by Sahiljawale** [comment]
Can I implement calculator in Python ?
If yes, can you assign me for this

**Comment by Vikash-8090-Yadav** [comment]
@Sahiljawale    are u making that  with help of  smart contract
