### ISSUE TITLE
Create a todo list smart contract

### ISSUE THREAD

**Issue by kunal232i** [Vikash-8090-Yadav/Solidity-Pathshala#104]
### Project title
Todo List

### Project Description
ToDo List smart contract in solidity
It can create tasks and store it into the array.

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
yes, Hacktoberfest
<hr/>

**Comment by kunal232i** [comment]
Can you assign this is to me..?

**Comment by Vikash-8090-Yadav** [comment]
start working on this @kunal232i

**Comment by AbhishekTiwari23** [comment]
I also want to work on it, but I have a doubt. Do I have to make a to-do list in any of the above languages, even in python? If yes then please assign it to me

**Comment by Vikash-8090-Yadav** [comment]
as of now u can't work on this issue because this assigns to @kunal232i . If u have new idea Raise the issue for the same . @AbhishekTiwari23 Hope u understand.

**Comment by daredevil3435** [comment]
Hey , can you tell me what exactly need to be done?

**Comment by Vikash-8090-Yadav** [comment]
@daredevil3435   sorry but this issue  is already completed  . I forget to close this , my bad . 

Merge PR  for this issue : https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/pull/114
