### ISSUE TITLE
Create a Counter Smart Contract Program

### ISSUE THREAD

**Issue by saikishore222** [Vikash-8090-Yadav/Solidity-Pathshala#108]
Smart Contract Program
(Write project title over here)

The owner of the smart contract able to Increase the Counter value and decrease the Counter value in the contract
(Describe the project over here)

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
Yes ,Hacktoberfest 2022

<hr/>

**Comment by saikishore222** [comment]
Please assign this task  to me under the hactoberfes

**Comment by Vikash-8090-Yadav** [comment]
Great idea @saikishore222 . Start working on this issue
