### ISSUE TITLE
Grammatical errors + Updating Readme Files

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#11]
There is an grammatical error in [SendTo_Eather.sol](https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/blob/main/Level1/sendTo_Eather/SendTo_Eather.sol) file inside of [Level1/sendTo_Eather](https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/tree/main/Level1/sendTo_Eather) folder. There is an error in file name and in folder name too. Can you please assign this issue to me!!

**Comment by Vikash-8090-Yadav** [comment]
> There is an grammatical error in [SendTo_Eather.sol](https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/blob/main/Level1/sendTo_Eather/SendTo_Eather.sol) file inside of [Level1/sendTo_Eather](https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/tree/main/Level1/sendTo_Eather) folder the same error is in the file name and in folder name too. Can u please assign this issue to me!!

It's better if u provide the screen shot  also .. for better understanding 
Thnak u

**Comment by AnmolSirola** [comment]
![Code](https://user-images.githubusercontent.com/95535448/181606774-9259a2bd-9ad7-4fcd-b625-836c85b7d316.png)
![FileName](https://user-images.githubusercontent.com/95535448/181606784-c2af503e-eccb-40f5-b7be-1f47ea7d0ed3.png)

**Comment by AnmolSirola** [comment]
Eather should be replaced with ether in both cases

**Comment by AnmolSirola** [comment]
![Code](https://user-images.githubusercontent.com/95535448/181607058-084243af-0d8c-4d1f-b9ea-e4ad50d73d96.png)
![FileName](https://user-images.githubusercontent.com/95535448/181607065-f51b461d-e3f9-4c74-aad0-634cb49bff1c.png)
Eather should be replaced with ether in both the cases

**Comment by Vikash-8090-Yadav** [comment]
okh look's great but i suggest you to check all the file's and folder and correct them . accordingly
 Along  with that create and  update the readme file for Level0 , Level1 , Level2 folder

is this fine ?

**Comment by AnmolSirola** [comment]
Yes Sir
