### ISSUE TITLE
create a smart contract that Implements Fall back Function

### ISSUE THREAD

**Issue by saikishore222** [Vikash-8090-Yadav/Solidity-Pathshala#111]
### Project title
create a smart contract that Implements Fall back Function

### Project Description
Fall back function is like unamed function it will execute when none of the other functions are not matched.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?

Yes, I am a Hactoberfest Contributor

<hr/>

**Comment by saikishore222** [comment]
@Vikash-8090-Yadav  can you please assign this task to me.

**Comment by Vikash-8090-Yadav** [comment]
@saikishore222  i guess this project is already  completed  . Look at once in my repo and let me know

**Comment by saikishore222** [comment]
> @saikishore222 i guess this project is already completed . Look at once in my repo and let me know

Yes. I changed the project and can you please look into it and assign me

**Comment by Vikash-8090-Yadav** [comment]
Nope this can create spam . u can create a issue for  Auction  price smart contract 
@saikishore222  . Hope this helps
