### ISSUE TITLE
Add Readme in Hello_World Folder

### ISSUE THREAD

**Issue by surjyaneeh** [Vikash-8090-Yadav/Solidity-Pathshala#12]
### Description of  the change
Add a Readme file in Hello_World Folder
![image](https://user-images.githubusercontent.com/75573569/182022850-5d26f0b0-8c29-4e20-9590-3bec6fe5e2fb.png)

### Domain 

- [x] Readme

#### Are you contributing under any open-source program?

HSOC'22

**Comment by Vikash-8090-Yadav** [comment]
Great idea !
Start working on it ..
