### ISSUE TITLE
Create a Flash Loan contract

### ISSUE THREAD

**Issue by nirban256** [Vikash-8090-Yadav/Solidity-Pathshala#125]
### Project title
Flash Loan

### Project Description
Flash Loan contract using aave defi protocol

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
Hacktoberfest
<hr/>

**Comment by nirban256** [comment]
@Vikash-8090-Yadav I want to work on this UNDER HACKTOBERFEST program.

**Comment by Vikash-8090-Yadav** [comment]
Looking great . Start  working  on this .

**Comment by nirban256** [comment]
@Vikash-8090-Yadav in which folder do I need to keep the contract folder?

**Comment by Vikash-8090-Yadav** [comment]
@nirban256  .Keep  this in level1 folder
