### ISSUE TITLE
Adding more codes to Level 0 folder

### ISSUE THREAD

**Issue by vryan-06** [Vikash-8090-Yadav/Solidity-Pathshala#126]
### Project title
Further improving Level 0 folder

### Project Description
I wish to add 2 or 3 more codes in the level 0 folder. This will help others to understand basics of solidity and smart contracs.
One of them will be to count number of distinct elements in array and so on.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
- [x] Hacktoberfest 2022

<hr/>

**Comment by vryan-06** [comment]
I want to work on this as a part of Hacktoberfest 2022. Kindly allow me @Vikash-8090-Yadav, thank you!

**Comment by Vikash-8090-Yadav** [comment]
@vryan-06 sorry to say this but currently i am not accepting any arthmethic code and basics of solidity is already done . 
I request to see the level1 or level2 folder and raise issue for this . 
Hope u understand . 
Thank u 🙂.

**Comment by vryan-06** [comment]
No worries!!

**Comment by vryan-06** [comment]
Should I edit this issue or create a new one for level1 folder changes? @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
@vryan-06  Kimdly create a new issue for this
