### ISSUE TITLE
Books DB

### ISSUE THREAD

**Issue by vryan-06** [Vikash-8090-Yadav/Solidity-Pathshala#127]
### Project title
Setting and Getting Books 

### Project Description
I wish to create a smart contract using which we will be able to store books with their title, author's name and id and then later on we can get the books using its id.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
- [x] Hacktoberfest 2022
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
please add the relevant name of the issue . write full form for Db also . 
Thank u @vryan-06

**Comment by vryan-06** [comment]
Done

**Comment by Vikash-8090-Yadav** [comment]
Great start  working on this issue . 
@vryan-06
