### ISSUE TITLE
Code to implement ERC-721 smart contracts

### ISSUE THREAD

**Issue by Harsh3363** [Vikash-8090-Yadav/Solidity-Pathshala#13]
### Project title
Code to implement ERC-721 smart contracts

### Project Description
solidity code for implementation of the ERC-721 token 

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
SSOC'22
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
@Harsh3363  please mention your open source programe name under "Are you contributing under any open-source program ?"

**Comment by Harsh3363** [comment]
> @Harsh3363 please mention your open source program name under "Are you contributing under any open-source program ?"

contributing under SSOC'22

**Comment by Vikash-8090-Yadav** [comment]
OK great . 
starting working on this  issue . 
and Raise P.R after 1 aug .

**Comment by Harsh3363** [comment]
> OK great . starting working on this issue . and Raise P.R after 1 aug .

Sure

**Comment by Vikash-8090-Yadav** [comment]
> > OK great . starting working on this issue . and Raise P.R after 1 aug .
> 
> Sure As I see you have divided programs into different levels please tell me in which level should I add my program in?
Push this in Level 2

**Comment by Harsh3363** [comment]
> > > OK great . starting working on this issue . and Raise P.R after 1 aug .
> > 
> > Sure As I see you have divided programs into different levels please tell me in which level should I add my program in?
> Push this in Level 2
> 

Sure 👍

**Comment by Vikash-8090-Yadav** [comment]
@Harsh3363 i am closing this issue as of now  ..  Make a fresh issue after the filling google  form as said in the stage call of ssoc'22

**Comment by Harsh3363** [comment]
Sure
