### ISSUE TITLE
Timer Smart contract 

### ISSUE THREAD

**Issue by saikishore222** [Vikash-8090-Yadav/Solidity-Pathshala#133]
Timer  Smart Contract
(Write project title over here)

Timer smart Contract makes the contract work in a certain time period, after a certain period it completed it raises an error time over.
(Describe the project over here)

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
yes, I am hactoberfest 2022 Contributor.

<hr/>

**Comment by saikishore222** [comment]
@Vikash-8090-Yadav can you assign this task to me.

**Comment by Vikash-8090-Yadav** [comment]
Great idea start working on this issue .
@saikishore222  include this in level 1 folder .
