### ISSUE TITLE
Library Contract

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#134]
### Project title
Library Contract

### Project Description
A library smart contract which allows us to add  a book( we can add the name of the book, its year and its author name) to our smart contract and we can set its status too as finished or unfinished.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?

Hackoberfest

<hr/>

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I would like to add this in level 1 folder.

**Comment by Vikash-8090-Yadav** [comment]
Great idea .Start working on this issue .

**Comment by Atoo35** [comment]
Is someone already working on this?

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola
