### ISSUE TITLE
Anonymous Polling Contract

### ISSUE THREAD

**Issue by SadashayKanungo** [Vikash-8090-Yadav/Solidity-Pathshala#135]
### Project title
Anonymous Polling Contract

### Project Description
A Smart contract that lets users create different Polls in the form of Multiple Choice Questions and other users can then cast their votes on these polls. The vote cast by a particular address is not stored on the contract, so it makes their choice anonymous.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?

 - [x] Hacktoberfest 202

**Comment by SadashayKanungo** [comment]
Hey @Vikash-8090-Yadav . I would like to add this contract to Level 2. Please assign me.

**Comment by Vikash-8090-Yadav** [comment]
GREAT IDEA . start working on this .@SadashayKanungo
