### ISSUE TITLE
ERC20 token contract

### ISSUE THREAD

**Issue by shobhit9070** [Vikash-8090-Yadav/Solidity-Pathshala#136]
### Project title
ERC20 token 

### Project Description
Create your own ERC20 token which can be imported to metmask and can be transfered using metamask and remix ide.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
Hacktoberfest 2022
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Ok , Ur idea seems to be cool and new . 
Start working on this .
