### ISSUE TITLE
Smart Contract for Dynamic NFTs

### ISSUE THREAD

**Issue by AyushPathak3011** [Vikash-8090-Yadav/Solidity-Pathshala#14]
### Project title
Dynamic NFT smart contract

### Project Description
A smart contract that helps in minting dynamic NFTs which evolve after an interval of time.

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
SSOC '22
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
@AyushPathak3011  i am closing this issue as of now .. Make a fresh issue after the filling google form as said in the stage call of ssoc'22
