### ISSUE TITLE
ERC20 Upgradable Smart Contract

### ISSUE THREAD

**Issue by Envoy-VC** [Vikash-8090-Yadav/Solidity-Pathshala#140]
### Project title
ERC-20 Upgradable Smart Contract

### Project Description
Build a ERC20 Upgradable contract that can be (kind of) altered, after the deployment.

### Domain

- [x] Solidity
- [x] JavaScript
- [x] Hardhat

#### Are you contributing under any open-source program ?

Hacktoberfest 2022

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
@Envoy-VC , is this issue similar to the #136 or u want to some modification in this .

**Comment by Envoy-VC** [comment]
No, It is a Upgradable ERC-20 Token which uses OpenZeppelin Upgradable smart contracts in which users can deploy a new version of the existing contract which uses features like delegate call to make easy for smart contracts fix bugs after they have been deployed.

**Comment by Vikash-8090-Yadav** [comment]
Great .Start working on this .
