### ISSUE TITLE
Add solidity books in the blog folder

### ISSUE THREAD

**Issue by shobhit9070** [Vikash-8090-Yadav/Solidity-Pathshala#142]
### Description of  the change
Add solidity books in the blog folder so user can have a deeper dive in the subject

### Domain 

- [x] Readme
- [x] Solidity

#### Are you contributing under any open-source program ?
hacktoberfest
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Sorry am currently no accepting the Blog's.

**Comment by Vikash-8090-Yadav** [comment]
hey if u want to write blogs then u can now proceed .As am accepting the blogs now .
@shobhit9070

**Comment by Vikash-8090-Yadav** [comment]
But the topics are not related to projects ...so this issue is not valid for blogs .If u have any new idea then u can raise the new issue .
Thank u .
