### ISSUE TITLE
Blog Smart Contract

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#149]
### Project title
Blog

### Project Description
A blog smart contract which allows users to create a blog and make posts to that blog . We can also create new posts and update them.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
Hackoberfest
<hr/>

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I would like to add this in level 1

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola  Great idea , start  working  on this .
