### ISSUE TITLE
Strings and bytes32

### ISSUE THREAD

**Issue by Envoy-VC** [Vikash-8090-Yadav/Solidity-Pathshala#151]
### Project title
Strings and Bytes32 in Solidity

### Project Description
Basic Tutorial on strings and bytes32 data in solidity, and comparing strings with cryptographic hash functions.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?

HacktoberFest 2022

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great starting working on this issue .and raise pr
