### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by samipashaa** [Vikash-8090-Yadav/Solidity-Pathshala#158]
I noticed this repository doesn't have a license.
If you don't mind I would like to add one to clarify what others can and can't do with this repository.

I was thinking the MIT license would work.

**Comment by Vikash-8090-Yadav** [comment]
SURE ..@samipashaa

**Comment by samipashaa** [comment]
Sorry wrong repository, can I add Code of Conduct.

**Comment by Vikash-8090-Yadav** [comment]
Closing in  preparation of SWOC'23
