### ISSUE TITLE
Dutch Auction

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#159]
### Project title
Dutch Auction

### Project Description
Seller of NFT deploys this contract, participants can bid by depositing ETH greater than the current highest bidder. All bidders can withdraw their bid if it is not the current highest bid.
### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
Hackoberfest
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
what does this means seller of nft ?

**Comment by AnmolSirola** [comment]
Basically the person who is selling the product in this case the product is NFT

**Comment by Vikash-8090-Yadav** [comment]
Great idea start working  on this .
