### ISSUE TITLE
Unresponsive Readme

### ISSUE THREAD

**Issue by legendarykamal** [Vikash-8090-Yadav/Solidity-Pathshala#16]
### Description of  the change
Readme on the main page is Unresponsive for mobile version

![Screenshot_2022-08-01_200151](https://user-images.githubusercontent.com/95926324/182173780-42a42304-2703-4419-aa79-d175a5f40dce.jpg)

### Domain 

- [x] Readme
- [] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes under SSOC
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
great issue  ! But i a/c to rules  u have to raise a issue only after filling  the form and sucessfully added in my project group in the discord . I will tell u there . Just wait for some time . As of  now i am closing  this issue .
 Thank u

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav can you reopen this , as now I have registered !

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal  sure ! do u wana to work  on this issue ?

**Comment by legendarykamal** [comment]
yes I want to work on this .

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal are u still working on this ?

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal   any updates ??

**Comment by SadashayKanungo** [comment]
Hi @Vikash-8090-Yadav I would like to work on this issue. Can you assign it to me?

**Comment by Vikash-8090-Yadav** [comment]
Sure @SadashayKanungo . Start  working on this
