### ISSUE TITLE
Freelancer smart contract

### ISSUE THREAD

**Issue by Omega12Pirme** [Vikash-8090-Yadav/Solidity-Pathshala#161]
it has three functions:

Employer deposit eth in smart contract, deposit().
Freelancer upload data, like a link with his work, upload().
Withdraw ether. withdraw(). 

Please assign this to me . i want to work on this . 
Thanks

**Comment by Vikash-8090-Yadav** [comment]
Great idea ,start working on this @Omega12Pirme

**Comment by Vikash-8090-Yadav** [comment]
Closing in  preparation of SWOC'23

**Comment by suyashmadhesia** [comment]
@Vikash-8090-Yadav can you please assign this task to me? I am from SWOC participants.

**Comment by Vikash-8090-Yadav** [comment]
Yah sure ! @suyashmadhesia Start working on this .

**Comment by suyashmadhesia** [comment]
@Vikash-8090-Yadav Hey I have created the smart contract for freelancer can you tell me where should I place this code in the level  1 or level 2 or level 3 directory of this repo? Should I have to write comments in the code or just explain the code in readme works?

**Comment by Vikash-8090-Yadav** [comment]
include this in level 1.

**Comment by Vikash-8090-Yadav** [comment]
Write comments if necessary . And readme is important !!
