### ISSUE TITLE
E-Voting DApp

### ISSUE THREAD

**Issue by apoorva1823000** [Vikash-8090-Yadav/Solidity-Pathshala#176]
### Project title
E-voting DApp

### Project Description
E-voting Decentralized application with more control functions that can be deployed on replit ide

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
Yes
<hr/>

**Comment by apoorva1823000** [comment]
I want to add this smart contract. Kindly assign me the work

**Comment by Vikash-8090-Yadav** [comment]
Yah sure  . Start  working on this @apoorva1823000 .

**Comment by Vikash-8090-Yadav** [comment]
Can  u please introduce yourself on  on the discussion of this community . As it's a Good  Habbit in open source . 

https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/discussions/175

**Comment by Vikash-8090-Yadav** [comment]
Start working on this and i ll assign u after the Announcement By SWOC

**Comment by apoorva1823000** [comment]
Hi, I introduced myself as well as added the smart contract too.

**Comment by Vikash-8090-Yadav** [comment]
@apoorva1823000 can u please tell how is  this different from the project   Voring in  level2 .

**Comment by apoorva1823000** [comment]
@Vikash-8090-Yadav sure sir,
In that one, on deploying we can see that it works efficiently but it can have only two participants whereas in my smart contract we can have as many number of participants as the owner desires to. Also you can register voters i.e. people who are allowed to vote so that no unauthorized participant can vote. Inreal world this compares to the fact that only citizen above 18 can vote whereas in the voting smart contract already present in level 2, there is no such limitation which puts a cap over its functionality and thus restricting it to be efficiently applicable in quite smaller domain

**Comment by apoorva1823000** [comment]
So will you approve my contribution ?
