### ISSUE TITLE
Write a  Blog  on "Smart Contract" used in Blockchain field 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Solidity-Pathshala#179]
Hey ,this  is the beginner friendly issue . So if anyone want's to take  please reply in comment .

Goal  ->

Think about smart contract and write a blog on  this 
For  format refrence see  the blog written in the "Blog" Folder  .
All the thing's should be in format with the images . 
Hope u understand  .

**Comment by SiddharthaMadhav** [comment]
Hi, I'm Siddhartha. Can I work on this?

**Comment by Vikash-8090-Yadav** [comment]
Hey @SiddharthaMadhav , sure u can work on this . Don't forget to introduce yourself in the community !
https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/discussions/175

**Comment by SiddharthaMadhav** [comment]
Hi solidity community, I'm Siddhartha. I am a student currently pursuing my B.Tech. at SASTRA University in Tamil Nadu. I'm pretty new to the blockchain space and want to contribute to the open source and have fun.

**Comment by monishkajha17** [comment]
Sir, can I work on it

**Comment by Vikash-8090-Yadav** [comment]
@monishkajha17 it's already  merged !!

**Comment by Vikash-8090-Yadav** [comment]
U can create a new issue for any for any blog's !
