### ISSUE TITLE
Improve the  hacktoberfest image in Readme.md

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Solidity-Pathshala#180]
As  the image quality is not good , and The  image background is also not matching with the readme background . 

Goal :

Improve the image , size should be same  , should be responsive in   desktop as well as in mobile . 

please Reply if u want to take this issue .

**Comment by Harshit-Raj-14** [comment]
please assign me this issue.

**Comment by Vikash-8090-Yadav** [comment]
Sure start working on this .

**Comment by Harshit-Raj-14** [comment]
Hello, I have made a PR for the issue can you please confirm if the changes are alright.

https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/pull/191

**Comment by Vikash-8090-Yadav** [comment]
Yup , all thing's are fine . Thank u !
