### ISSUE TITLE
FIR smart contract

### ISSUE THREAD

**Issue by apoorva1823000** [Vikash-8090-Yadav/Solidity-Pathshala#183]
### Project title
FIR smart contract

### Project Description
I wish to add a smart contract for FIR system to the repo as a contribution for the community to learn real life usage of smart contracts

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program?
yes
<img width="261" alt="fir" src="https://user-images.githubusercontent.com/71769587/210602098-c2a6d5ac-196c-42e8-b68c-ca8ae561a842.png">

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Sure  , start working on this . Just tell me the folder name in which u want to add .

**Comment by apoorva1823000** [comment]
level 1 would be good i guess for this project
