### ISSUE TITLE
Smart contract for chat app

### ISSUE THREAD

**Issue by Saksham-1612** [Vikash-8090-Yadav/Solidity-Pathshala#184]
### Project title
Smart Contract for a chat dapp

### Project Description
A smart contact for chat dapp which has features like add friend , read message , send message and other functionalities.

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
- SWOC S3

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this . @Saksham-1612
