### ISSUE TITLE
Lottery system smart contract

### ISSUE THREAD

**Issue by apoorva1823000** [Vikash-8090-Yadav/Solidity-Pathshala#190]
### Project title
Lottery system smart contract

### Project Description
I wish to add a lottery system smart contract in the level 1 of this repo 

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
yes
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
@apoorva1823000 i guess there  is  already lottery smart contract in Solidity-Pathshala

**Comment by apoorva1823000** [comment]
I saw in level 0,1 and 2 but there was no project for lottery system by this name so I thought its not there

**Comment by Vikash-8090-Yadav** [comment]
> I saw in level 0,1 and 2 but there was no project for lottery system by this name so I thought its not there

Alright then , Do this in Level 2 folder . ✌️
