### ISSUE TITLE
Event organization 

### ISSUE THREAD

**Issue by DevSwayam** [Vikash-8090-Yadav/Solidity-Pathshala#192]
### Project title
Event organization

### Project Description
The event organization contract will have 2 entities :
   1) Event organizer.
   2) Attendee.
A organizer will create event and will make tickets so that attendee can buy those tickets and enjoy event  

### Domain
- [] Solidity
- [] JavaScript

#### Are you contributing under any open-source program ?
yes
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Ya great.Start working on this . Include this in level2 folder .

**Comment by ankit2025** [comment]
can i start working on this
