### ISSUE TITLE
Equal Distribution of Funds using smart contract

### ISSUE THREAD

**Issue by DevSwayam** [Vikash-8090-Yadav/Solidity-Pathshala#199]
### PROJECT DESCRIPTION
There are two entities in this project: 
  1) A person owner of funds=
       A person who has a property can divide and equally distribute his property to his relatives after they get x years old (for example 
        18 years old)
   2) A beneficiar =
           beneficiars will get equally distributed funds after they gets x years old.

### Features :
   1)A owner can add more funds.
   2)A owner can add  or delete beneficiars.

### Domain
[x] Solidity
[x] Remix

### Are you contributing under any open-source program ?
yes

**Comment by Vikash-8090-Yadav** [comment]
Great issue @DevSwayam .Start working in this .

**Comment by DevSwayam** [comment]
> Great issue @DevSwayam .Start working in this .
to include in which level?

**Comment by Vikash-8090-Yadav** [comment]
> > Great issue @DevSwayam .Start working in this .
> to include in which level?
> 

Level 1

**Comment by DevSwayam** [comment]
Task completed. Contract added in level 1 names as funds distribution
