### ISSUE TITLE
Create Issue temaplate 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Solidity-Pathshala#2]
Greetings of the day folks !!
If anyone want's to create the issue template then feel free to comment 

The issue template should contains ->  **Bug report , Feature request  and  other .** 
like shown below 

![Screenshot from 2022-07-25 17-32-13](https://user-images.githubusercontent.com/85225156/180774570-b7a320bb-2b7c-4543-8a2d-d1d27d2ee9f0.png)

**Comment by surjyaneeh** [comment]
@Vikash-8090-Yadav Can You assign it to me?
And I have doubt about where should I include that issue_template.md file.

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav Can You assign it to me? And I have doubt about where should I include that issue_template.md file.

Yeah sure !

create .github/ISSUE_TEMPLATE/add-project.md , custom.md , imporevements.md

and this folder should be in the root directory only .
