### ISSUE TITLE
Adding readme for Level 1 folder and Correcting all the grammatical errors.

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#20]
### Description of  the change
Adding readme for Level 1 folder and Correcting all the grammatical errors.

### Domain 
- [x] Readme
- [x] Documentation

#### Are you contributing under any open-source program ?

SSOC'22
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
can u please tell in which folder u want to add readme  ,   with the file name ?

**Comment by AnmolSirola** [comment]
FolderName Level 1\senTo_eather

**Comment by Vikash-8090-Yadav** [comment]
Great @AnmolSirola  start working on it
