### ISSUE TITLE
Lottery Smart Contract

### ISSUE THREAD

**Issue by prakhar3062** [Vikash-8090-Yadav/Solidity-Pathshala#201]
### Project Description
It is going to have three phase-:

1. The first is open, where new numbers can be submitted by anyone for a small fee
2. The second is closed, where no new numbers can be submitted and the random number is being generated. 
3. The third is finished, where the number has been generated and the winner has been paid.
If no one wins, the lottery contract can be rolled over, increasing the jackpot
### Features
The advent of verifiable randomness on the blockchain reduces the amount of complexity in lotteries
### Domain

- Solidity
- Remix
### Are you contributing under any open-source program ?
yes

**Comment by Vikash-8090-Yadav** [comment]
Hey @prakhar3062 sorry for the late reply . Can u pleasew check level1 and level2 folder , I guess  there  is same file exist in that . please check once

**Comment by prakhar3062** [comment]
Sorry, I checked and found a contract related to the lottery system
