### ISSUE TITLE
Echai Full stack Dapp

### ISSUE THREAD

**Issue by DevSwayam** [Vikash-8090-Yadav/Solidity-Pathshala#203]
#### Project Description :
Echai full stack web app using React, ethers.js and hardhat for testing.
   
#### FEATURES: 
A user can donate fund worth of a chai amount to developers(owner) who deployed the site with a message attached to it.
A user can view how many funds the dapp holds.
A user can see whole list of donators from start to latest up to date with their message and funds.

#### Text Stack used:
[x] Solidity
[x] Ethers
[x] React
[x] HardHat
[x] remix

#### Are you contributing under any open source program:
Yes

**Comment by Vikash-8090-Yadav** [comment]
@DevSwayam   please raise this issue in Web3-Wrold repo  . As this repo only consist  smart contract files . 
Thank's

**Comment by DevSwayam** [comment]
> @DevSwayam please raise this issue in Web3-Wrold repo . As this repo only consist smart contract files . Thank's

Okk 👍

**Comment by DevSwayam** [comment]
how can i close this issue
