### ISSUE TITLE
Bike rental smart contract on binance smart chain

### ISSUE THREAD

**Issue by DevSwayam** [Vikash-8090-Yadav/Solidity-Pathshala#204]
### Project Description :
It is a smart contract for Bike rental industry owner.
#### The contract is made for Three entities:
1) owner:
who earns specific money by providing bike for specific time.
2) Renter : 
who rents bikes and provide money according to time he use.
3) Bike:
Every bike has its own specification.

### Project Feature:
The calculation of rental money will be always accurate without using a third party manger all payments will done via binance credit.

### Text Stack :
[x] Solidity
[x] Remix
[x] Binance smart chain

### Are you contributing under any open source program :
Yes (swoc 2023)

**Comment by Vikash-8090-Yadav** [comment]
Gr8 start working on this . @DevSwayam

**Comment by Vikash-8090-Yadav** [comment]
Include this in level1

**Comment by Vikash-8090-Yadav** [comment]
> Continue with  thiS ISSUE ONLY  and include all the function in this only

**Comment by DevSwayam** [comment]
ok

**Comment by DevSwayam** [comment]
Smart contract is merged hence i am closing this issue.
