### ISSUE TITLE
Multi signature wallet

### ISSUE THREAD

**Issue by Kaushan-Dutta** [Vikash-8090-Yadav/Solidity-Pathshala#209]
### Description

**Project Description**
Based on the DAOs ideology, a decision can only be implemented after a certain percentage of owner votes for it.

**Problem it Solves**
Most of the time we see that to make a transaction happen we need the signature of a single owner, which means that he controls all the authorization but let suppose what if we distribute the power to more than one person so that when any transaction will happen we need to have the signature of all the owners and based upon majority we will decide whether the transaction will happen or not.

**Technologies**
- [x] Solidity
- [x] Hardhat
- [x] Ethers.js
- [x] Open zeppelin

**Comment by Kaushan-Dutta** [comment]
Can you check it please

**Comment by Vikash-8090-Yadav** [comment]
Yah wait . checking @Kaushan-Dutta

**Comment by Kaushan-Dutta** [comment]
Going to do both of them

**Comment by Vikash-8090-Yadav** [comment]
Okh , so include the Smart contract thing in this repo only and  for the Full stack refer the Web3 World . 
Hope u understand !.
