### ISSUE TITLE
Add readme.md files for all the folders inside level 2 i.e Marketplace and Voting.

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#21]
### Description of  the change
Add readme.md files for all the folders inside(Marketplace) level 2.

### Domain 

- [x] Readme

#### Are you contributing under any open-source program ?

SSOC'22

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great issue start working on it !
