### ISSUE TITLE
Ether Price fetcher.

### ISSUE THREAD

**Issue by DevSwayam** [Vikash-8090-Yadav/Solidity-Pathshala#210]
### Smart Contract Description:
A ether price fetcher is a smart contract fetches live ether price(OFFCHAIN DATA) without relying on frontend which is normally use in UniSwap, ParaSwap.
The main goal is to fetch this data using chainlink oracle and bring it in smart contract so that it wont need to rely on any other front end application to constantly write on blockchain to update data.

### Text Stack Used :
 [x] Solidity

### Are you contributing under any program ?
Yes (Swoc 2023)

**Comment by Vikash-8090-Yadav** [comment]
what type of data u will fetch and show ?
and how many data u will show ?

**Comment by DevSwayam** [comment]
> what type of data u will fetch and show ? and how many data u will show ?

I will be fetching eth to usd using chainlink contract address basically using inheritance. Its simple smart contract which show independent fetching of live offchain data without reling on frontend.

**Comment by Vikash-8090-Yadav** [comment]
Check #197

**Comment by DevSwayam** [comment]
> Check #197

somone already implemented it sorry
