### ISSUE TITLE
Smart Contract for dynamic NFTs

### ISSUE THREAD

**Issue by AyushPathak3011** [Vikash-8090-Yadav/Solidity-Pathshala#24]
### Project title
Dynamic NFT smart contract

### Project Description
A smart contract that helps in minting dynamic NFTs which evolve after an interval of time.

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
SSOC '22
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great idea . Start working on it ! @AyushPathak3011

**Comment by Vikash-8090-Yadav** [comment]
@AyushPathak3011  ??

**Comment by Vikash-8090-Yadav** [comment]
if u are taking part in hackatoberfest . open this  issue and  ping me . @AyushPathak3011
