### ISSUE TITLE
changement- Grammer errors

### ISSUE THREAD

**Issue by AnshuMishra01** [Vikash-8090-Yadav/Solidity-Pathshala#25]
### Description of  the change

Grammer/Typos Errors in the files which are named below.

###Files

1. Level0/Greeting/README.md
2. Level2/Marketplace/Marketplace.sol
3. Level2/banking/banking.sol

#### Are you contributing under any open-source program?

SSOC

**Comment by Vikash-8090-Yadav** [comment]
@AnshuMishra01  Thank's for your Issue i think some one is already working on it . U can check #22
