### ISSUE TITLE
Adding comment in the Hello world solidity file

### ISSUE THREAD

**Issue by TripathiShyaamal** [Vikash-8090-Yadav/Solidity-Pathshala#27]
### Description of  the change
Some things like view and memory keywords need to be clear for a person looking at the code for the first time.

### Domain 
- [x] Solidity

#### Are you contributing under any open-source program ?

SSOC

**Comment by Vikash-8090-Yadav** [comment]
@TripathiShyaamal thank for creating this issue ..
if u  want to add the comment then add to all the code file avialbale in the directory? 
is that ok ?

**Comment by snehasharma76** [comment]
I would like to contribute to this issue. Kindly assign me this issue.

**Comment by Vikash-8090-Yadav** [comment]
@TripathiShyaamal are u working on this issue ?

**Comment by TripathiShyaamal** [comment]
Yes I am already working on the issue.
