### ISSUE TITLE
Buy Me A Coffee Smart Contract

### ISSUE THREAD

**Issue by AyushPathak3011** [Vikash-8090-Yadav/Solidity-Pathshala#28]
### Project title
Buy Me A Coffee Smart Contract

### Project Description
With the help of this smart contract, users will be able to tip the owner of the smart contract with Ethereum. The owner can then withdraw the tips from the smart contract.

### Domain

- [x] Solidity
#### Are you contributing under any open-source program?
SSOC '22
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
> ### Project title
> Buy Me A Coffee Smart Contract
> 
> ### Project Description
> With the help of this smart contract, users will be able to tip the owner of the smart contract with Ethereum. The owner can then withdraw the tips from the smart contract.
> 
> ### Domain
> 
> - [x] Solidity
> #### Are you contributing under any open-source program?
> SSOC '22
> <hr/>
> 

ok start working on  this issue! I will assign u later ...!
