### ISSUE TITLE
CrowdFunding smartcontract

### ISSUE THREAD

**Issue by kunal232i** [Vikash-8090-Yadav/Solidity-Pathshala#29]
### Project title
CrowdFunding smartcontract

### Project Description
New Campaign -> Users will be able to start a new crowdfunding project by entering campaign details such as the title, story, and goal amount to be raised.
View Project ->users can view all of the existing projects and campaign details.
Make Donation -> 	Anyone can donate to a project they want to support.

### Domain

- [x] Solidity

**Comment by Vikash-8090-Yadav** [comment]
@kunal232i  great idea ! start working on it

**Comment by kunal232i** [comment]
> @kunal232i great idea ! start working on it

Sure 😄
