### ISSUE TITLE
Create P.R template 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Solidity-Pathshala#3]
Greetings of the day folks !!
If anyone want's to create the issue template then feel free to comment
The template should look like this  shown below 

![Screenshot from 2022-07-25 18-06-45](https://user-images.githubusercontent.com/85225156/180779696-b850affc-8e15-4945-8ed8-f32f7d3d56d2.png)

**Comment by surjyaneeh** [comment]
@Vikash-8090-Yadav 
May I work on this issue?

**Comment by Vikash-8090-Yadav** [comment]
Yah sure !

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav 
> May I work on this issue?

Start working on this issue i will assign u whenever i get free  ,will assign u later ..don't worry 😄

**Comment by surjyaneeh** [comment]
> > @Vikash-8090-Yadav
> > May I work on this issue?
> 
> Start working on this issue i will assign u whenever i get free ,will assign u later ..don't worry 😄

Okay

**Comment by Vikash-8090-Yadav** [comment]
here , create these check list ->

[] Project using only Solidity
[] [] Project using only Javascript
[] Project using only Python
[] Project Test on the Remix IDE
[] Mention below if project uses other language and ide .

@surjyaneeh  please update these chnages to the P.R template then i will add the label's
all set to go smile

**Comment by surjyaneeh** [comment]
> here , create these check list ->
> 
> [] Project using only Solidity [] [] Project using only Javascript [] Project using only Python [] Project Test on the Remix IDE [] Mention below if project uses other language and ide .
> 
> @surjyaneeh please update these chnages to the P.R template then i will add the label's all set to go smile

These will be in place of Domain of Contribution, right?

**Comment by Vikash-8090-Yadav** [comment]
> > here , create these check list ->
> > [] Project using only Solidity [] [] Project using only Javascript [] Project using only Python [] Project Test on the Remix IDE [] Mention below if project uses other language and ide .
> > @surjyaneeh please update these chnages to the P.R template then i will add the label's all set to go smile
> 
> These will be in place of Domain of Contribution, right?
YES
