### ISSUE TITLE
Creating our own crypto coin (which allows only creator to create new coins).

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#32]
### Project title
Crypto Coin

### Project Description
The contract allows only its creator to mint new coins.
Anyone can send coins to each other without the need of registering (with a username and password) all u need is a ethereum keypair.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
SSOC'22

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great idea !  start working on it . 
Can u please tell the folder structure in which u waana to  push this .

**Comment by AnmolSirola** [comment]
I'll add it in level 2 (create  a new folder of crypto coin).

**Comment by Vikash-8090-Yadav** [comment]
ok fine
Happy learning :smile:

**Comment by ishani02** [comment]
@Vikash-8090-Yadav  Is the issue still open?

**Comment by Vikash-8090-Yadav** [comment]
if u are taking part in hackatoberfest . open this  issue and  ping me . @Sanitya7  @ishani02

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola

**Comment by ishani02** [comment]
> if u are taking part in hackatoberfest . open this issue and ping me . @Sanitya7 @ishani02

yes I am taking part in Hacktoberfest 2022

**Comment by Vikash-8090-Yadav** [comment]
raise the new @ishani02  for hacktoberfest 2022 .

**Comment by ishani02** [comment]
ok
