### ISSUE TITLE
Adding more codes to Level0 folder

### ISSUE THREAD

**Issue by vryan-06** [Vikash-8090-Yadav/Solidity-Pathshala#34]
There are only 2 codes so far in the Level0 folder. 
I wish to add few more codes to that folder.

**Comment by Vikash-8090-Yadav** [comment]
great ! start working on it ... @vryan-06

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav get me assigned for this one, I would like to add some contrib in this area :+1:

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav get me assigned for this one, I would like to add some contrib in this area :+1: 

Please what type of contribution u wana to do ? And which u wana to add

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav 
1> a contract explaining function modifiers like view vs pure when to use what.
2> Reversing an array
3> checking palindrome for strings (currently we have just for numbers)
...

**Comment by Vikash-8090-Yadav** [comment]
> 

@legendarykamal   great idea ... Create a new issue regarding this .. 
Thank u
