### ISSUE TITLE
Sum of two integers

### ISSUE THREAD

**Issue by Sanitya7** [Vikash-8090-Yadav/Solidity-Pathshala#35]
### Project Title
Arithmetic Operators - Programs 

### Project Description
A simple but handy program for beginners( Level 0 ), showing addition of two integers 
This program gives 
- Addition of Two Numbers
- Subtraction of Two Numbers 
- Multiplication of Two Numbers 
- Division of Two Numbers 

🔹   Addition of Two Numbers : 
```
pragma solidity 0.6.0;
contract sum_of_num{
    int public num1;
    int public num2;
    int public sum;
    //Function for sum of two numbers
    function add(int a, int b) public 
    {
        num1 = a ;
        num2 = b ;
        sum = num1 + num2;
    }
    //Function for printing sum of two numbers
    function print_sum() public view returns ( int )
    {
        return sum ; 
    }
}
```
🔹   Subtraction of Two Numbers 
```
pragma solidity ^0.6.0;
contract Sub
{
    function get_sub( int x, int y ) public view returns ( int )
    {
        int num1 = x ;
        int num2 = y ;
        int result = x - y ;
        return result ;
    }
}
```
🔹  Multiplication of Two Numbers :
```
pragma solidity ^0.6.0;
contract Product_of_num
{
    function get_product(int x, int y ) public view returns ( int )
    {
        int num1 = x ;
        int num2 = y ;
        int product = num1 * num2 ;
        return product ;
    }
}
```
🔹  Division of Two Numbers :
```
pragma solidity ^0.6.0 ;
contract division 
{
    int public divisor ;
    int public dividend ;
    int public quotient ; 
    int public remainder ; 
    function do_division(int x,int y) public 
    {
        divisor =  x ;
        dividend = y ;
        quotient = y / x ;
        remainder = y % x ; 
    }
}
```

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
yes, SSOC'22
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
@Sanitya7  great issue ! but along this i would highly recommend u to make sub  , div , multiplication along this . 
is this ok?

**Comment by Sanitya7** [comment]
Sure, I will be adding the basics soon ! 
Thanks @Vikash-8090-Yadav 👍

**Comment by Sanitya7** [comment]
Hi @Vikash-8090-Yadav , I have added the add, sub, mul & division in the issue.
Check it out! 
In two program I have used local and in two of them I have used state variables, do let me know if you want it to change it.

**Comment by Vikash-8090-Yadav** [comment]
> Hi @Vikash-8090-Yadav , I have added the add, sub, mul & division in the issue. Check it out! In two program I have used local and in two of them I have used state variables, do let me know if you want it to change it.

NO issue, all look's great .. Raise a P.R for this .. Thank u

**Comment by Sanitya7** [comment]
👍

**Comment by Vikash-8090-Yadav** [comment]
if u are taking part in hackatoberfest . open this  issue and  ping me . @Sanitya7
