### ISSUE TITLE
Understanding structs, their implementation and memory and storage keywords' implementation

### ISSUE THREAD

**Issue by TripathiShyaamal** [Vikash-8090-Yadav/Solidity-Pathshala#36]
### Project title
Storage_memory

### Project Description
Adding file for understanding structs, their implementation and memory and storage keywords' implementation

### Domain
- [x] Solidity

#### Are you contributing under any open-source program ?

SSOC

<img width="619" alt="File" src="https://user-images.githubusercontent.com/76724036/183261807-e6c2bec2-b9ee-4c8f-987d-916fd187ad76.png">

**Comment by Vikash-8090-Yadav** [comment]
please tell the folder structure in which u want to add @TripathiShyaamal

**Comment by TripathiShyaamal** [comment]
Folder name: Storage_Memory and inside File.sol and readme file

**Comment by Vikash-8090-Yadav** [comment]
ok start working on this @TripathiShyaamal
