### ISSUE TITLE
Defi App

### ISSUE THREAD

**Issue by legendarykamal** [Vikash-8090-Yadav/Solidity-Pathshala#41]
### Project title
A decentralised Finance Buy me a coffee dApp

### Project Description
(Describe the project over here)
Buy me a coffee is found on various websites but you need a credit card for doing it. The idea is to take it on the blockchain and ease the effort 
### Domain

- [x] Solidity
- [x] JavaScript

#### Are you contributing under any open-source program ?
SSOC22
<hr/>

**Comment by legendarykamal** [comment]
// @Vikash-8090-Yadav Pls get me assigned :)

**Comment by legendarykamal** [comment]
ok so I just found that there is a smart contract already https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/pull/30 merged 
So should i work on frontend and then integrating it with the contract ?

**Comment by Vikash-8090-Yadav** [comment]
Open new issue in the web3.0-world repo ..

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal  close this issue

**Comment by legendarykamal** [comment]
OK
