### ISSUE TITLE
Adding a new feature

### ISSUE THREAD

**Issue by legendarykamal** [Vikash-8090-Yadav/Solidity-Pathshala#42]
### Description of  the change

Currently https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/tree/main/Level1/Coin allows only owner to mint coin.

We can add a feature for 
1> anybody to mint 
2> putting restrictions on the number of coins to be minted.

### Domain 

- [x] Readme
- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
SSOC22
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
ya sure u can modify this .. 
Great idea @legendarykamal

**Comment by legendarykamal** [comment]
yeah thank you 
I have completed this task // @Vikash-8090-Yadav
