### ISSUE TITLE
Fix typos in README.md

### ISSUE THREAD

**Issue by legendarykamal** [Vikash-8090-Yadav/Solidity-Pathshala#44]
### Description of  the change
Describe more about the change.
There are various typos in https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/blob/main/Level1/Coin/Readme.md
which give worst reading experience, these need to be fixed !
### Domain 

- [x] Readme

#### Are you contributing under any open-source program ?
SSOC22
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal can u please mention or share the ss of the particular typo .
