### ISSUE TITLE
Adding more codes to Level0 folder

### ISSUE THREAD

**Issue by legendarykamal** [Vikash-8090-Yadav/Solidity-Pathshala#45]
### Project title
(Write project title over here)
A new list of contracts based upon explaining pure vs view + other smart contracts.

### Project Description

1> a contract explaining function modifiers like view vs pure when to use what.
2> Reversing an array
3> checking palindrome for strings (currently we have just for numbers)

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal  ?? Any updates

**Comment by legendarykamal** [comment]
yes I will add the PR by today @Vikash-8090-Yadav :+1:

**Comment by Vikash-8090-Yadav** [comment]
if u are taking part in hackatoberfest . open this  issue and  ping me . @legendarykamal
