### ISSUE TITLE
Notes on Solidity from Loom Network

### ISSUE THREAD

**Issue by TripathiShyaamal** [Vikash-8090-Yadav/Solidity-Pathshala#46]
I will create a seperate file named Solidity_Notes and add the solidity notes there itself.

**Comment by Vikash-8090-Yadav** [comment]
what is Loom Netwrok @TripathiShyaamal

**Comment by TripathiShyaamal** [comment]
> what is Loom Netwrok @TripathiShyaamal 

It is a website for courses and I pursued the course of making CryptoZombies game from there. 

https://cryptozombies.io/en/course/

**Comment by legendarykamal** [comment]
> I will create a seperate file named Solidity_Notes and add the solidity notes there itself.

how will this be helpful @TripathiShyaamal ?

**Comment by TripathiShyaamal** [comment]
It has the complete notes required for someone who wants to learn Solidity.

**Comment by Vikash-8090-Yadav** [comment]
have u makes notes from yourshlef or just copied from that site ?

**Comment by TripathiShyaamal** [comment]
Ofc I make them myself and I have pasted the ss of some codes so that if in future I need to go through these then there won't be any problem.

Moreover these notes were made by me during a competition where we had to complete the course and show them our learnings in which I also won 25 USDT, so there is no point that I have copied or something.

**Comment by Vikash-8090-Yadav** [comment]
congratulations ! U can now work on this ...
Issue @TripathiShyaamal
