### ISSUE TITLE
Creating a Wallet with various useful functions

### ISSUE THREAD

**Issue by legendarykamal** [Vikash-8090-Yadav/Solidity-Pathshala#47]
### Project title
Creating a wallet  

### Project Description
With the help of which a user can 
1> deposit ether to his wallet ,
2> send ether to another account and 
3> check his own ether account balance.

This also comes with various restrictions imposed like only the owner can transfer ether to the reciever which is much needed in this case.
### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
SSOC22
<hr/>

**Comment by ASHISHKUMAR2411** [comment]
Hey,  I would like to work on this issue.

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal are u still working on this ?

**Comment by Kali-Decoder** [comment]
I love to do this task .. Sir

**Comment by legendarykamal** [comment]
hey everyone thanks for showing interest but this I guess already has been implemented.

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav I am modifying this to an advanced version of creating a wallet, So please assign me this task.
I have updated the description :+1:

**Comment by legendarykamal** [comment]
// @Vikash-8090-Yadav Please assign me and review the PR thanks

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav this would be added in the level2 folder can we atleast have intermediate label for this ?

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal  nope as u done only the basics things . Better try next time
