### ISSUE TITLE
Some great Solidity tools and integrated environment to learn

### ISSUE THREAD

**Issue by ASHISHKUMAR2411** [Vikash-8090-Yadav/Solidity-Pathshala#48]
### Project title
Some Solidity Tools to get started with 

### Project Description
To create a readme file for some great solidity tools and integration with examples which makes writing solidity easy and robust. 
### Domain

- [] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program?
SSOC
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
please elaborate more @ASHISHKUMAR2411

**Comment by Vikash-8090-Yadav** [comment]
> I wanted to talk about some tools like in Remix ide we have an option for ABI generation, but how to generate abi for smart contracts and vice versa using some other tools, there are some tools available for them, basically referring to this [article](https://docs.soliditylang.org/en/v0.8.14/resources.html#solidity-tools)

@TripathiShyaamal are u including all this in your study material that mentioned above

**Comment by TripathiShyaamal** [comment]
Not these exactly but somethings about ABI.

**Comment by Vikash-8090-Yadav** [comment]
@ASHISHKUMAR2411  u can work on this issue ...now

**Comment by ASHISHKUMAR2411** [comment]
Thank you so much for assigning it to me, I would like to ask in which folder like level0, level1, or level2, I should add this project.

**Comment by Vikash-8090-Yadav** [comment]
Creat a folder Study_Material and then push this into that
