### ISSUE TITLE
Data Types in Solidity

### ISSUE THREAD

**Issue by ASHISHKUMAR2411** [Vikash-8090-Yadav/Solidity-Pathshala#49]
### Project title
Data types in Solidity

### Project Description
An Ultimate guide on data types of Solidity, A great place to get started with solidity and its data types. 

### Domain

- [] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
SSOC
<hr/>

**Comment by ASHISHKUMAR2411** [comment]
I would like to work on this issue.

**Comment by Vikash-8090-Yadav** [comment]
@ASHISHKUMAR2411   this issue can be done in the previous issue that is #50

**Comment by Vikash-8090-Yadav** [comment]
> Okay Great, I will do that, I first thought to keep them in separate files as First about Data types and then about modifiers, events, etc. Nevertheless i will create in one file

@TripathiShyaamal are u including all this in your study material that mentioned above

**Comment by TripathiShyaamal** [comment]
Ya I'll be including these.

**Comment by Vikash-8090-Yadav** [comment]
@ASHISHKUMAR2411 sorry but this issue will be cover in #46
