### ISSUE TITLE
Structure of a Smart Contract

### ISSUE THREAD

**Issue by ASHISHKUMAR2411** [Vikash-8090-Yadav/Solidity-Pathshala#50]
### Project title
Structure of a Smart Contract

### Project Description
Each contract can contain declarations of State Variables, Functions, Function Modifiers, Events, Errors, Struct Types, and Enum Types. Showing examples of each of the declarations. 

### Domain

- [] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program?
SSOC
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
OK just tell  me one thing  you  will be making a separate file for each code or  all these in one file function by function ?
@ASHISHKUMAR2411

**Comment by ASHISHKUMAR2411** [comment]
I wanted to describe them in one file function by function, and a README file for an explanation, and purpose.

**Comment by Vikash-8090-Yadav** [comment]
@TripathiShyaamal Are u including this also in your notes ?

**Comment by TripathiShyaamal** [comment]
I have pasted some parts of code at various instances so yeah it basically covers these.

**Comment by Vikash-8090-Yadav** [comment]
@ASHISHKUMAR2411  sorry u can't work  on this issue as this is already  under process #46 :smile:
