### ISSUE TITLE
Creating NFTs

### ISSUE THREAD

**Issue by ASHISHKUMAR2411** [Vikash-8090-Yadav/Solidity-Pathshala#51]
### Project title
About NFT and its Creation

### Project Description
> About NFT
> How to create a NFT and sell them
### Domain

- [] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
SSOC
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
can u please be more elaborate what u  wana to do ? @ASHISHKUMAR2411

**Comment by ASHISHKUMAR2411** [comment]
I would like to talk about NFT first, what are they, how they work in the readme file, solidity code on how to create nft and mint them, and if possible i will write solidity code on how to transfer the NFT.

**Comment by Vikash-8090-Yadav** [comment]
@ASHISHKUMAR2411  yes u can work on this .. Make sure to check that whether this file  exsit  in directory or not

**Comment by ASHISHKUMAR2411** [comment]
I have checked, and this file does not exist in the directory, I would like to ask in which folder like level0, level1, or level2, I should add this project.

**Comment by Vikash-8090-Yadav** [comment]
in level 1

**Comment by legendarykamal** [comment]
@ASHISHKUMAR2411 on which network are you looking to deploy your NFT's?

**Comment by legendarykamal** [comment]
@ASHISHKUMAR2411 on which network are you looking to deploy your NFT's?
