### ISSUE TITLE
Modifying sendTo_Ether contract 

### ISSUE THREAD

**Issue by legendarykamal** [Vikash-8090-Yadav/Solidity-Pathshala#53]
### Description of  the change

Modifying and bringing new changes to https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/tree/main/Level1/sendTo_Ether

This currently has these problems ->
1. No step by step guide for new users to use the smart contract.
2. Balance returns in default Wei which is 12 digit and quite confusion to new users.
3. Does not cover the end cases i.e. what if the contract has 0 balnce or the contract has more balance than to be transferred or both have equal balance.

### Domain 

- [x] Readme
- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
SSOC22
<hr/>

**Comment by legendarykamal** [comment]
hi @Vikash-8090-Yadav  can you assign this intermediate and assign it to me? 
This will involve both changes in the Readme and contract.

**Comment by Vikash-8090-Yadav** [comment]
Nope for l i can't cux ur justing editing the readme and  improving the existing one ... Hope u understand for  the intermediate u can make blog smart contract , nft , marketplace , dao ect
