### ISSUE TITLE
Removing repetitive work 

### ISSUE THREAD

**Issue by legendarykamal** [Vikash-8090-Yadav/Solidity-Pathshala#56]
### Description of  the change
Describe more about the change.

We are taking the same ss of compiling and deploying process which is becoming a friction as it is the same process in any contract , 
So we can make a simple file to tell everyone of how to run the contract on Remix.
### Domain 

- [x] Readme
- [] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [x] Other , feel free to mention below

#### Are you contributing under any open-source program ?
SSOC22
<hr/>

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav let me know of your thoughts on this

**Comment by Vikash-8090-Yadav** [comment]
Graet issue @legendarykamal  start working on this
