### ISSUE TITLE
Basics of the Blockchain

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Solidity-Pathshala#57]
### Write a blog on Basics of the Blockchain . 
**This file should be under :-> Blog/Basic of blockchain/Readme.md**
**Made image folder if  u r using any image under the blog section.**
f anyone want's  take this issue feel free to comment . Below are the points need to keep in mind while writing blog 

1. Introduction
2. Pre requesite
3. Main content
4. Flow diagram 
5. Conclusion
6. Refrence

**Comment by legendarykamal** [comment]
HI , I would like to work on this @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
ya sure @legendarykamal

**Comment by Vikash-8090-Yadav** [comment]
Any updates ??

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav In progress

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal  complete  this also .
