### ISSUE TITLE
Add Gitpod and improve the readme 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Solidity-Pathshala#59]
Do all the changes according to this P.R  in solidity-Pathshala  repo 

https://github.com/Vikash-8090-Yadav/Web3.0-World/pull/42

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I would like to work on this issue . But Sir, can u tell me what all things I should add and edit.

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola  see this pr  in the web.0-world .
You can easily see the code for this 
....
https://github.com/Vikash-8090-Yadav/Web3.0-World/pull/42/commits/03571c521a20bce84b4bec734c8e0c03191ea223

**Comment by Vikash-8090-Yadav** [comment]
![IMG_20220907_005033](https://user-images.githubusercontent.com/85225156/188721153-b7518b53-be14-4231-9f95-a53ff522cc17.jpg)
See the code for this only and include that code at the same place in Solidity-Pathshala readme .
HOPE U UNDERSTAND ☺️ @AnmolSirola

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav Okay Sir, I would like to work on this issue
