### ISSUE TITLE
Creating a ERC-721 Contract

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#62]
### Project title
ERC-721 Contract

### Project Description
Making a ERC-721 smart contract which fulfills all the requirement of erc-721 standard.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
SSOC

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
HIi @AnmolSirola  can u please explain more about this !

**Comment by Vikash-8090-Yadav** [comment]
check #51  once. and let me know if urs is diffrent

**Comment by AnmolSirola** [comment]
The issue #51 gives theory knowledge about NFT's and  gives solidity code on how to transfer the NFT. Mine is different , I will write the whole Solidity contract and add the functions of a real erc721 contract to it.

**Comment by Vikash-8090-Yadav** [comment]
ok @AnmolSirola  start working on this !

**Comment by Vikash-8090-Yadav** [comment]
yes @AnmolSirola start working on this !

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav Kindly look at the pr. Thank you
