### ISSUE TITLE
How to use Remix ide 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Solidity-Pathshala#68]
In this you have to tell how anyone beginner can use the remix  Ide in this you have to cover these topics as follow :

1.  Introduction 
2. why to use remix (with diagram )  
3. How  to deploy , compile , where is abi , byte code 
4. How to give the input 
5. Where to see the oputput 
6. Refrence if any

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I would like to work on this issue

**Comment by Vikash-8090-Yadav** [comment]
Sure @AnmolSirola

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I have prepared the required file . But in which folder should I add this ?

**Comment by Vikash-8090-Yadav** [comment]
I Blog section  make a folder name like How to use Remix idea 
Folder structure 

Blog/How to use remix/How to use remix.md
