### ISSUE TITLE
A smart contract about Abstract Contracts 

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#73]
### Project title
Abstract Contracts 

### Project Description
I want to write a smart contract which tells about abstract contracts and also explaining it in general.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
SSOC
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
can u please tell about the folder structure ?

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav Study Material/Advance Solidity

**Comment by Vikash-8090-Yadav** [comment]
Ok start doing this ..I will assign by eod .
