### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#76]
### Project title
Interface in Solidity

### Project Description
A smart contract which tells us about interface in solidity 

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
SSOC
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Ig this issue is already there in the level0 .please check once and let me know ..@AnmolSirola

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav No Sir, it's not there in level 0

**Comment by Vikash-8090-Yadav** [comment]
Ok start working on this  @AnmolSirola

**Comment by Vikash-8090-Yadav** [comment]
please specify the folder  structure

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav StudyMaterial/Solidity_Basics

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav Can I create a pr for this issue ?

**Comment by Vikash-8090-Yadav** [comment]
Yes @AnmolSirola Go ahead
