### ISSUE TITLE
Polymorphism

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#79]
### Project title
Polymorphism in Solidity

### Project Description
A smart contract which tells us about Polymorphism in solidity 

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
SSOC
<hr/>

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav I want to add this smart contract in the StudyMaterial/Advance_Solidity Folder

**Comment by Vikash-8090-Yadav** [comment]
Yes @AnmolSirola Great idea
