### ISSUE TITLE
Solidity basic syntax with code

### ISSUE THREAD

**Issue by TripathiShyaamal** [Vikash-8090-Yadav/Solidity-Pathshala#80]
### Project title
Solidity basic syntax with code

### Project Description
The file contains the code containing everything related to Solidity like: Data types, Inheritance, Interfaces, Eth transfer and various other operations. It will be better to understand from the notes that I previously uploaded and then looking at this code. 

### Domain
- [x] Solidity

#### Are you contributing under any open-source program ?
SSOC
<img width="919" alt="b" src="https://user-images.githubusercontent.com/76724036/189769670-513b6fb4-a8e8-442f-8bc6-e7d97cfc9929.png">
<img width="920" alt="a" src="https://user-images.githubusercontent.com/76724036/189769679-a8ddbaf8-c5b2-4950-aa27-24aa2b829c4e.png">

**Comment by Vikash-8090-Yadav** [comment]
Ig its already there is study material ur it

**Comment by TripathiShyaamal** [comment]
Yes it is there, but this is a sol file with comments so there might be some areas which might be hard to guess from notes so the sol file code will help them.

**Comment by Vikash-8090-Yadav** [comment]
ok tell me  the folder structure in which u wana put this file ?

**Comment by TripathiShyaamal** [comment]
Study Material -> code.sol. Works ?

**Comment by Vikash-8090-Yadav** [comment]
include this in Study_Material->Soliditty_Basics->Basics->All basics in solidity.sol
