### ISSUE TITLE
Require

### ISSUE THREAD

**Issue by AnmolSirola** [Vikash-8090-Yadav/Solidity-Pathshala#86]
### Project title
Require

### Project Description
Explaining what is require and how to use it in our code , because it is very important to know .

### Domain
- [x] Solidity

#### Are you contributing under any open-source program ?
SSOC

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
It Already  present  Go and check if that file contains some bugs then raise a issue to correct that file .

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav  Can you tell where it is present I cant find it in any folder

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav  Can you tell where it is present I cant find it in any folder

ok then create a p.r for this file
