### ISSUE TITLE
Need tests

### ISSUE THREAD

**Issue by SecondPort** [Vikash-8090-Yadav/Solidity-Pathshala#88]
Tests and automations are needed in hardhat/truffle, when a function is added/modified the test is run and it is clarified if everything works the same as always

**Comment by Vikash-8090-Yadav** [comment]
can u  please explain what u wana to do with this , means what;e the main aim of this  file .

**Comment by Vikash-8090-Yadav** [comment]
@SecondPort  ?? any updates
